import { bootstrapApplication } from '@angular/platform-browser';
import { RouteReuseStrategy, provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { HttpClientModule, provideHttpClient, withInterceptors } from '@angular/common/http';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';
import { addIcons } from 'ionicons';
import {
  alertCircleOutline,
  arrowForwardOutline,
  batteryCharging,
  batteryChargingOutline,
  batteryDeadOutline,
  businessOutline,
  cameraOutline,
  checkmarkCircle,
  checkmarkCircleOutline,
  banOutline,
  closeOutline,
  documentTextOutline,
  chevronDownOutline,
  chevronUpOutline,
  flashOutline,
  informationCircleOutline,
  listOutline,
  locateOutline,
  lockClosedOutline,
  locationOutline,
  logOutOutline,
  mapOutline,
  peopleOutline,
  personAddOutline,
  personOutline,
  phonePortraitOutline,
  powerOutline,
  qrCodeOutline,
  refreshOutline,
  scanOutline,
  navigateOutline,
  walletOutline,
  warningOutline,
} from 'ionicons/icons';

addIcons({
  alertCircleOutline,
  arrowForwardOutline,
  batteryCharging,
  batteryChargingOutline,
  batteryDeadOutline,
  businessOutline,
  cameraOutline,
  checkmarkCircle,
  checkmarkCircleOutline,
  banOutline,
  closeOutline,
  documentTextOutline,
  chevronDownOutline,
  chevronUpOutline,
  flashOutline,
  informationCircleOutline,
  listOutline,
  locateOutline,
  lockClosedOutline,
  locationOutline,
  logOutOutline,
  mapOutline,
  peopleOutline,
  personAddOutline,
  personOutline,
  phonePortraitOutline,
  powerOutline,
  qrCodeOutline,
  refreshOutline,
  scanOutline,
  navigateOutline,
  walletOutline,
  warningOutline,
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
    provideHttpClient(),
    HttpClientModule,
  ],
});
